---

# The gitlab_git_data_dir is the location where all the Git repositories will be stored. 
# You can use a shared drive or any path on the system.

gitlab_git_data_dir: "/srv/gitlab/git-data"

# The gitlab_backup_path is the location where Gitlab backups will be stored.

gitlab_backup_path: "/srv/gitlab/backups"



