---
galaxy_info:
  author: Robert de Bock
  namespace: robertdebock
  role_name: docker_ce
  description: Install and configure Docker CE on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: "2.10"

  platforms:
    - name: Debian
      versions:
        - buster
    - name: EL
      versions:
        - 8
    - name: Fedora
      versions:
        - 33
        - 34
    - name: Ubuntu
      versions:
        - focal
        - bionic

  galaxy_tags:
    - dockerce
    - docker

dependencies: []
