---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
    requirements-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
driver:
  name: docker
lint: "${MOLECULE_SCENARIO_DIRECTORY}/linters.sh"
platforms:
  - name: "centos6-${INSTANCE_UUID:-1}"
    image: centos:6
    dockerfile: Dockerfile.centos6.j2
    groups:
      - molecule_hosts
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: centos:7
    groups:
      - molecule_hosts
  - name: "centos8-${INSTANCE_UUID:-1}"
    image: centos:8
    groups:
      - molecule_hosts
  - name: "fedora33-${INSTANCE_UUID:-1}"
    image: fedora:33
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
  - name: "fedora34-${INSTANCE_UUID:-1}"
    image: fedora:34
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_enabled: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          check_platform_distributions:
            centos: 6
            debian: 9
            redhat: 6
            fedora: 27
          check_platform_variables:
            - check_platform_distributions
verifier:
  name: ansible
