---
#
# Ansible managed
#
repository:
  description: Install and configure Docker CE on your system.
  homepage: https://robertdebock.nl/
  topics: dockerce, docker, ansible, molecule, tox, playbook, hacktoberfest
