---
# Role dependencies

galaxy_info:
  role_name: proxy_client
  namespace: amtega
  author: Juan Antonio Valiño García
  description: Setup proxy client environment variables
  company: AMTEGA - Xunta de Galicia
  license: GPLv3 or EUPL
  min_ansible_version: 2.10
  platforms:
    - name: GenericLinux
      versions:
        - all
  galaxy_tags:
    - system
    - http
    - proxy
    - client

dependencies: []
