---

- name: check entropy state
  command: "cat /proc/sys/kernel/random/entropy_avail"
  changed_when: false
  register: entropy
- name: entropy state
  debug: var=entropy
- name: apt | Ensure have enough randomness
  apt:
    name:
      - rng-tools
#      - gnupg
      - gpgv2
## https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user
      - acl
    state: present
    update_cache: yes
  when: >
    (ansible_distribution == 'Debian' and ansible_distribution_version|int >= 7) or
    (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int >= 14)
  become: yes
  register: pkg_result
  until: pkg_result is success
- name: apt | Ensure have enough randomness
  apt:
    name:
      - rng-tools
      - gnupg
    state: present
    update_cache: yes
  when: >
    (ansible_distribution == 'Debian' and ansible_distribution_version|int < 7) or
    (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int < 14)
  become: yes
  register: pkg_result
  until: pkg_result is success

- name: yum | Ensure have enough randomness
  yum:
    name:
      - haveged
      - rng-tools
      - gnupg
      - acl
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"
  become: yes
  register: pkg_result
  until: pkg_result is success
- name: Enable haveged - redhat
  service: name=haveged state=started enabled=yes
  become: yes
  when: >
    ansible_os_family == "RedHat" and
    not (ansible_virtualization_type is defined and ansible_virtualization_type == "docker")
- name: check entropy state
  command: "cat /proc/sys/kernel/random/entropy_avail"
  changed_when: false
  register: entropy2
- name: entropy state
  debug: var=entropy2

- debug: var=ansible_ssh_user
- debug: var=ansible_user
- debug: var=gpg_generator_user
- debug: var=gpg_user
- debug: var=gpg_home

- name: Ensure .gnupg config directory exists with right permissions
  file:
    dest: "{{ gpg_home }}/.gnupg"
    state: directory
    mode: '0700'
    owner: "{{ gpg_generator_user }}"

- name: set defaut gpg options
  template:
    src: gpg.conf.j2
    dest: "{{ gpg_home }}/.gnupg/gpg.conf"
    mode: '0600'
    owner: "{{ gpg_generator_user }}"
- name: copy default template for gpg key generation
  template:
    src: gen-key-script
    dest: "{{ gpg_home }}/.gnupg/gen-key-script-{{ gpg_user }}"
    mode: '0600'
    owner: "{{ gpg_generator_user }}"

- include: gpg21.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int > 16

## Note: matching on realname or email doesn't allow to create multiple keys. alternative?
- name: check existing secret key
  shell: "gpg --list-secret-keys | grep '{{ gpg_realname }}'"
  changed_when: false
  ignore_errors: true
  become: yes
  become_user: "{{ gpg_generator_user }}"
  register: gpgkeys
  no_log: "{{ gpg_no_log }}"
- debug:
    var: gpgkeys
    verbosity: 2
  no_log: "{{ gpg_no_log }}"

- name: generate gpg key
  command: "gpg --batch --gen-key {{ gpg_home }}/.gnupg/gen-key-script-{{ gpg_user }}"
  args:
    chdir: "{{ gpg_home }}"
  become: yes
  become_user: "{{ gpg_generator_user }}"
  when: gpgkeys is defined and not gpgkeys.stdout
  register: genkey
  no_log: "{{ gpg_no_log }}"

#- debug: var=genkey
- name: GPG<2.1 | import generated keys
  command: "gpg --import {{ gpg_home }}/{{ gpg_pubkeyfile }} {{ gpg_home }}/{{ gpg_privkeyfile }}"
  become: yes
  become_user: "{{ gpg_generator_user }}"
  when: >
    gpgkeys is defined and not gpgkeys.stdout and
    not (
          (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int > 16) or
          (ansible_os_family == "RedHat" and ansible_distribution_major_version|int > 7)
        )

- name: GPG2.1+ | import generated keys
  command: "gpg --import {{ gpg_home }}/{{ gpg_pubkeyfile }}"
  become: yes
  become_user: "{{ gpg_generator_user }}"
  when: >
    gpgkeys is defined and not gpgkeys.stdout and
    (
      (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int > 16) or
      (ansible_os_family == "RedHat" and ansible_distribution_major_version|int > 7)
    )

- name: get user gpg fingerprint
  shell: |
     set -o pipefail
     gpg --list-keys --keyid-format LONG {{ gpg_useremail }} | awk -F'[ /]' '/sub/ { print $5 }' | tee {{ gpg_home }}/{{ gpg_fingerprint }}
  args:
    executable: /bin/bash
    creates: "{{ gpg_home }}/{{ gpg_fingerprint }}"
  register: gpg_user_fingerprint
  become: yes
  become_user: "{{ gpg_generator_user }}"
- name: get user armored public key
  shell: "gpg --export -a {{ gpg_useremail }} > {{ gpg_home }}/{{ gpg_pubkeyfileexport }}"
  changed_when: false
  become: yes
  become_user: "{{ gpg_generator_user }}"

- debug: var=gpg_pull
- name: fetch files to orchestrator
  fetch: "src={{ item }} dest={{ gpg_pulldir }}/ flat=yes"
  with_items:
#    - "{{ gpg_home }}/{{ gpg_privkeyfile }}"
#    - "{{ gpg_home }}/{{ gpg_pubkeyfile }}"
    - "{{ gpg_home }}/{{ gpg_pubkeyfileexport }}"
    - "{{ gpg_home }}/{{ gpg_fingerprint }}"
  when: gpg_pull is defined and gpg_pull

- name: fetch privatekey file to orchestrator
  fetch: "src={{ item }} dest={{ gpg_pulldir }}/ flat=yes"
  with_items:
    - "{{ gpg_home }}/{{ gpg_privkeyfile }}"
  when: gpg_pull is defined and gpg_pull and gpg_pull_privatekey is defined and gpg_pull_privatekey
