---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-centos7-gitlab
    image: ami-9887c6e7
    platform: centos7
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family

  - name: test-aws-ubuntu1804-gitlab
    image: ami-012fd5eb46f56731f
    platform: ubuntu18
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family

  - name: test-aws-ubuntu1804-gitlab-11.0.0
    image: ami-012fd5eb46f56731f
    platform: ubuntu18
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family
      - gitlab_11.0.0

  - name: test-aws-debian9-gitlab
    image: ami-003f19e0e687de1cd
    platform: debian9
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family

  - name: test-aws-debian9-gitlab-11.0.0
    image: ami-003f19e0e687de1cd
    platform: debian9
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family
      - gitlab_11.0.0

provisioner:
  name: ansible
  inventory:
    group_vars:
      gitlab_11.0.0:
        gitlab_version: 11.0.0
  log: false
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    prepare: ../resources/provisioning/AWS/prepare.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws-direct
verifier:
  name: testinfra
  options:
    verbose: true
  directory: ../resources/tests/
  lint:
    name: flake8
